[package]
name = "sout_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4.14"
mlua = {version = "0.10.3",features = ["lua53"]}

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-args=-rdynamic"]